### ISSUE TITLE
Menu Won't Expand on Hover

### ISSUE THREAD

**Issue by montelco** [CodyHouse/mega-site-navigation#2]
I can't get the menu to expand when hovering. Is there a work-around for this?

**Comment by claudia-romano** [comment]
Hi there, the menu expands on click (hover event was not included). 
If you need it to expand on hover, you should try replacing the click event with the hover one (in the js code, search for the 'open submenu' comment and try replacing the on 'click' with on 'hover'). 
Cheers!

**Comment by montelco** [comment]
Hi Claudia,

Yes, replacing click with hover works but it causes the menu to disappear when trying to navigate to the secondary menu that drops down. You can prevent this by triggering click on mouseover but this has the added bug of requiring a second mouseover to close the secondary menu.
